### ISSUE TITLE
在webstorm中的.vue文件中支持.scss语法

### ISSUE THREAD

**Issue by yaoningvital** [yaoningvital/blog#16]
在写.vue文件中的样式时，在` <style> `标签中最开始用的是原始的css文件，不能写.scss，写sass的样式时，webstorm不能识别。会出现下面的错误：

![Alt text](https://raw.githubusercontent.com/yaoningvital/MarkdownImages/master/images/github-blog/not-recognize-scss.png "Optional title")

解决办法是：

1. 安装相应的依赖(` sass-loader ` 、` node-sass ` 、` vue-style-loader `、` scss-loader `)：
``` npm install sass-loader node-sass vue-style-loader scss-loader --save-dev ```

1. 在style标签上添加` rel="stylesheet/scss" `。这样，webstorm中style标签部分的.scss语法就能识别了。如下图所示：
![Alt text](https://raw.githubusercontent.com/yaoningvital/MarkdownImages/master/images/github-blog/recognize-scss.png "Optional title")

另：
在*.vue模板中支持几种css预处理器和模板语言jade。但是当你在<style>标签中加上 lang=sass 然后写sass时会发现IDE一片报错。一开始想到的是webstorm的Language Injections，并照着已有的写了一个：

![Alt text](https://raw.githubusercontent.com/yaoningvital/MarkdownImages/master/images/github-blog/webstorm-language-injections.png "Optional title")

然而并不能用。。。
发现了<style>标签中有 rel="stylesheet/scss"和 type="text/css" 时能正确识别sass语言。其实我试了以后发现，type="text/css" 也可以不需要。如：

```
<style scoped lang="scss" rel="stylesheet/scss">
```
这样就能让webstorm识别sass了。同理less也可以。但是需要webstorm版本高于2016.1.1 。

**Comment by jiayaqin123** [comment]
thank you

**Comment by EvenRsh** [comment]
添加 type="text/scss" 
```
<style scoped lang="scss" type="text/scss" >
```
